### ISSUE TITLE
Allow users to easily support the project financially

### ISSUE THREAD

**Issue by patcon** [mvarnagiris/expensius#2]
A "pro" or "donate" app variant ideally.

And in my situation, hopefully implemented in such a way that I can pay buy purchasing the app on Google Play, but then install via F-Droid

(For others, +1 this if you'd like to be made aware when this becomes available.)

**Comment by andreskrey** [comment]
+1

I've been using this app so much and became practically part of my daily rutine. I would love to support the developer.

**Comment by xxoolltt** [comment]
Why I can't find the package "com.mvcoding.financius.ui.Presenter;"
I cannot compile this program ! 
Please Help me ! Thanks!

**Comment by mvarnagiris** [comment]
Here's what I'm thinking at the moment:
- Most of the app will be free.
- In-depth reports will be paid.
- Ability to turn on in-depth reports without paying but by enabling ads.

**Comment by patcon** [comment]
that sounds really progressive :)

**Comment by philipgiuliani** [comment]
Sounds like a very good idea. Never saw this concept so far. What i found really interesting is this app: https://play.google.com/store/apps/details?id=de.stollenmayer.philipp.Pop_1_1_Android after some levels there is a "Pay as much as its worth to you" screen. You could do that to unlock all features with a start price of 5€ for example. So if somebody wants to pay more, he can.

**Comment by mvarnagiris** [comment]
That is a really good idea, I will do that. Not sure about the prices though. Probably best is to set it per country basis otherwise it would be unfair for poorer countries.

**Comment by mvarnagiris** [comment]
This is partly done. I've created other issues to track progress for donations and ads.
#10 #11
